apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: container-second
          image: ichih/second
          imagePullPolicy: Always
          env:
            - name: HOST
              value: service-first
            - name: PORT
              value: "6666"
          volumeMounts:
            - mountPath: /tmp
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-pvc
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: service-second
#spec:
#  type: ClusterIP
#  selector:
#    app: second
#  ports:
#    - port: 3333 # service listen port
#      targetPort: 3333 # target listen port
#apiVersion: v1
#kind: Service
#metadata:
#  name: service-mock-gateway
#spec:
#  type: ClusterIP
#  selector:
#    app: mock-gateway
#  ports:
#    - port: 3333
#      targetPort: 3333
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-cashier-v2-api
#  annotations:
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/group.name: cashier
#    alb.ingress.kubernetes.io/group.order: "31"
#spec:
#  rules:
#    - host: "api.xjun.tw"
#      http:
#        paths:
#          - pathType: Prefix
#            path: /
#            backend:
#              service:
#                name: service-cashier-v2-api
#                port:
#                  number: 80